//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbCollegeEntities : DbContext
    {
        public dbCollegeEntities()
            : base("name=dbCollegeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblStudent> tblStudents { get; set; }
        public virtual DbSet<tblCourse> tblCourses { get; set; }
        public virtual DbSet<tblCourseSubject> tblCourseSubjects { get; set; }
        public virtual DbSet<tblGrade> tblGrades { get; set; }
        public virtual DbSet<tblStudentSubject> tblStudentSubjects { get; set; }
        public virtual DbSet<tblSubject> tblSubjects { get; set; }
        public virtual DbSet<tblTeacher> tblTeachers { get; set; }
        public virtual DbSet<v_CourseSubject> v_CourseSubject { get; set; }
        public virtual DbSet<v_StudentSubject> v_StudentSubject { get; set; }
        public virtual DbSet<v_Subject> v_Subject { get; set; }
        public virtual DbSet<tblStudentGrade> tblStudentGrades { get; set; }
        public virtual DbSet<v_StudentGrade> v_StudentGrade { get; set; }
    }
}
